name: GoImports Check

on:
  pull_request:
    paths:
      - '**/*.go'

jobs:
  check-goimports:
    name: Check GoImports
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install goimports
      run: go install golang.org/x/tools/cmd/goimports@latest

    - name: Get changed files
      id: files
      uses: lots0logs/gh-action-get-changed-files@v1.2
      with:
        format: 'space-delimited'

    - name: Check goimports
      run: |
        echo "Changed Files: ${{ steps.files.outputs.all }}"
        for file in ${{ steps.files.outputs.all }}; do
          if [[ $file == *.go ]]; then
            goimports -l $file
            if [ $? -ne 0 ]; then
              echo "::error file=$file::File does not conform to goimports style"
              exit 1
            fi
          fi
        done
      shell: bash

