name: Go quality checks

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.go'

jobs:
  check-goimports:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled to ensure git history is available for git-diff.

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21' # Using repo corresponding go version

      - name: Install goimports
        run: go install golang.org/x/tools/cmd/goimports@latest

      - name: Check goimports
        run: |
          git fetch origin main:refs/remotes/origin/main 
          FILES=$(git diff --name-only --diff-filter=d origin/main...HEAD | grep '\.go$')
          if [ -n "$FILES" ]; then
            goimports -l -d $FILES
            if [ $(goimports -l $FILES | wc -l) -gt 0 ]; then
              echo "goimports must be run on the following files:"
              goimports -l $FILES
              exit 1
            fi
          fi

  unit-tests:
    name: Unit Tests
    needs: check-goimports
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.21' # Using repo corresponding go version

      - name: Run Unit Tests
        run: go test ./... -cover
