name: GoImports Check

on:
  pull_request:
    paths:
      - '**/*.go'

jobs:
  check-goimports:
    name: Check GoImports
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install goimports
      run: go install golang.org/x/tools/cmd/goimports@latest

    - name: List all changed files
      id: get-file
      run: |
        echo "FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '.go$')" >> $GITHUB_ENV

    - name: Check goimports
      run: |
        FILES=${FILES}
        echo "Checking files: $FILES"
        for FILE in $FILES; do
          goimports -l $FILE
          if [ $? -ne 0 ]; then
            echo "::error file=$FILE::File does not conform to goimports style."
            exit 1
          fi
        done
